### ISSUE TITLE
TODO List: Navigation

### ISSUE THREAD

**Issue by sean6bucks** [sean6bucks/berylsays#1]
Create svg font for social icons and Main logo

##### Styling

- [x] Add hover state for navigation items - CSS
- [x] Add active state animation and placement for underline - JS
- [x] Add hover state for social icons - CSS

##### Navigation

- [x] On navigation click run navigation function for interaction
- [x] Set current page
- [x] Show / hide Contact page if not current
- [x] Show / Hide About Page if not current
- [x] Social Icon clicks lead to proper pages
