### ISSUE TITLE
TODO List: Page Loading

### ISSUE THREAD

**Issue by sean6bucks** [sean6bucks/berylsays#2]
##### Initial Load
- [x] Create page loading shade element - DOM /CSS
- [x] Add animation to loading icon/text to show loading UX - CSS
- [x] On load complete fade out shade - JS / CSS
- [x] On Load complete animate Icon to the corner? - JS?

##### Project Load
- [x] Set same page loader for Project load?
