### ISSUE TITLE
TODO: Projects

### ISSUE THREAD

**Issue by sean6bucks** [sean6bucks/berylsays#3]
#### Projects Page

- [x] Add hover states to client project items
- [x] Add hover states to event project items
- [x] Add hover states to illustration item
- [x] Set click behavior on project element - whole element? just title?
- [x] On click set loading UX and trigger specific project page

##### Layout
?

##### Loading / Animation

- [x] On complete load animate in project page
- [x] Figure out animation/interaction of project page and loading shade?
